#!/bin/bash

# $OSTYPE is in {"linux-gnu", "darwin", "freebsd"}

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

source $DIR/vars
source $DIR/weather.sh
source $DIR/battery.sh
source $DIR/cpu-temp.sh
source $DIR/rts-bus.sh

WIDGETS=(weather battery cpu-temp)

CUR_HOUR=$( date +%H )
if [ $CUR_HOUR -gt 19 ] && [ $CUR_HOUR -lt 22 ]; then
  WIDGETS+=(rts-bus)
fi

EPOCH=$( date +%s )
TENS=$((EPOCH / 10))

WIDGET_OUT=$( ${WIDGETS[$(( TENS % ${#WIDGETS[@]} ))]} )

# pad some space
# from https://stackoverflow.com/a/4411098/1291435
OUT="                             "
printf "%s%s " "${OUT:${#WIDGET_OUT}}" $WIDGET_OUT
